### ISSUE TITLE
[Feature Contribution]: Implement stale issue github actions

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#318]
### What happened?

_As_ the Carbon Aware SDK working group
_I want to_ enable [stale for actions](https://github.com/actions/stale)
_So that_ I reduce overhead of inactive issues and review the backlog faster

In order to help the team manage the issues more easily, we would like to enable automatically labelling stale issues and closing inactive stale issues as documented here https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues

We understand that common practice is to have maximum 60 days for stale issues.
In order for that change to transition smoothly, we will want issues that are older than 6 months old to be closed automatically.
To that end, we will start with the following settings:
```yaml
          days-before-issue-stale: 120
          days-before-issue-close: 60
```

This sits under https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/252

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

**Comment by danuw** [comment]
On reflection, and to align with our original 6 months, i have used the following:

```yaml
        days-before-issue-stale: 240 # ~6 months old 
        days-before-issue-close: 20 # further 20 days
        days-before-pr-stale: 120 # ~3 months old
```

**Comment by danuw** [comment]
Messages have also been updated to the following:

```yaml
        stale-issue-message: 'This issue has not had any activity in 240 days. Please review this issue and ensure it is still relevant. If no more activity is detected on this issue for the next 20 days, it will be closed automatically.'
        close-issue-message: 'This issue has not had any activity for too long. If you believe this issue has been closed in error, please contact an administrator to re-open, or if absolutly relevant and necessary, create a new issue referencing this one. '
        stale-pr-message: 'This a stale pull request. Please review, update or/and close as necessary.'
```
